# Site settings
title: IDEAL智能大数据管理与分析实验室
email: bolongzheng@whut.edu.cn
description: >-
  实验室简介，专注于时序分析、时空数据挖掘与向量检索等前沿研究领域。
baseurl: ""
url: ""

# Contact information
address: "湖北省武汉市珞狮路122号学海楼512 "
postal_code: "430070"
contact_email: "bolongzheng@whut.edu.cn"

# Navigation
navigation:
  - title: 首页
    url: /
  - title: 团队动态
    url: /blog/
  - title: 研究方向
    url: /research/
  - title: 团队成员
    url: /team/
  - title: 学术成果
    url: /achievements/
  - title: 加入我们
    url: /joinus/

# Collections
collections:
  research_articles:
    output: true
    permalink: /research/articles/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/
  - scope:
      path: ""
      type: "research_articles"
    values:
      layout: "research_article"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
